version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - DBURL=mongodb://test5:123@mongo:27017/mongodb?authSource=admin
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongo
    networks:
      - mongo-networks

  frontend:
    build: ./frontend
    ports:
      - "5173:3000"
    depends_on:
      - backend
    networks:
      - mongo-networks

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test5
      - MONGO_INITDB_ROOT_PASSWORD=123
      - MONGO_INITDB_DATABASE=mongodb
    volumes:
      - mongo-data:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d:ro
    networks:
      - mongo-networks

volumes:
  mongo-data:
